<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>transponder-parent</artifactId>
		<groupId>org.orienteer.transponder</groupId>
		<version>1.1-SNAPSHOT</version>
	</parent>

	<artifactId>transponder-janusgraph</artifactId>

	<name>transponder-janusgraph</name>

	<dependencies>
		<dependency>
			<groupId>org.orienteer.transponder</groupId>
			<artifactId>transponder-core</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.janusgraph</groupId>
			<artifactId>janusgraph-core</artifactId>
			<version>1.1.0</version>
		</dependency>
		<dependency>
			<groupId>org.janusgraph</groupId>
			<artifactId>janusgraph-inmemory</artifactId>
			<version>1.1.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.tinkerpop</groupId>
			<artifactId>gremlin-core</artifactId>
			<version>3.7.3</version>
		</dependency>
		<dependency>
			<groupId>org.orienteer.transponder</groupId>
			<artifactId>transponder-core</artifactId>
			<version>${project.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>